### ISSUE TITLE
latest and/or greatest lambda

### ISSUE THREAD

**Issue by lukewalshct** [mohamedhayibor/messing-with-alexa#11]
https://gist.github.com/lukewalshct/e6a50aa6415bff475ce4340971170ab4

**Comment by mohamedhayibor** [comment]
WhatStation what station is available
WhatStation what is my favorite station
WhatStation what's my station
WhatStation what is my station
WhatStation my station
WhatStation my favorite station
WhatStation get my station
WhatStation get my favorite station
WhatStation give me my favorite station
WhatStation give me my station
WhatStation what my station is
WhatStation what my favorite station is
WhatStation yes
WhatStation yup
WhatStation sure
WhatStation yes please
GetStationsIntent your station is {GetStations}
